export const FOLLOW_UP_OVERLAY_Z_INDEX = 2147483645;
export const TOOL_ACTIVITY_OVERLAY_Z_INDEX = FOLLOW_UP_OVERLAY_Z_INDEX + 1;
export const APPROVAL_MODAL_Z_INDEX = TOOL_ACTIVITY_OVERLAY_Z_INDEX + 1;
